pipeline {
  agent any
  
  stages {
    stage("paso 1"){
     
      steps {		
        echo 'hola mundo'
      }
    }
  }
    post {
      always {          
        echo 'fase always'
      }
      success {
        echo 'fase success'
        }

      failure {
        echo 'fase failure'
      }
      
  }
} 

